Dev/ngis spec v3.22/new gel1004 message
WMRGL/PlaterPlotter pull request #48
Opened 2023-08-29 10:01 UTC by ReubenMonaghan

2023-08-30 11:07 UTC, joelarkman requested changes
Hi Reuben,

These changes are looking good and pretty much ready to merge, i've just added a few thoughts, questions and one suggestion that I wanted to run past you before we action the pull request.

Many thanks,
Joe

2023-08-30 11:07 UTC, joelarkman commented on platerplotter/platerplotter/holding_rack_manager.py
> +			if sample.is_repeat == "New" and sample.sample_delivery_mode != "Family Only":
Just trying to think through all the various combinations to see if there are any scenarios where these ANDs should actually be ORs but I think we are okay - I guess we're only needing to add an extra exclusion to when this code used to be triggered.

2023-08-30 15:40 UTC, ReubenMonaghan commented on platerplotter/platerplotter/models.py
> +	sample_delivery_mode = models.CharField(max_length=50, blank=True, default="Standard", choices=(("Tumour First", "Tumour First"),
I think I just need to check importing old Gel1004 messages work on the BI test server, but I ran the migrate command with no issues.

2023-08-30 15:44 UTC, ReubenMonaghan reviewed
Need to remove "" from accepted_values in check_sample_delivery_mode() views.py line 190.

2023-09-05 10:11 UTC, joelarkman approved these changes
Hi Reuben,

Thanks for making the changes, this looks good and ready to merge to me.

Many thanks,
Joe

2023-09-05 11:10 UTC, merged